### ISSUE TITLE
Issue with "npm run build" - Missing "dist" directory

### ISSUE THREAD

**Issue by petervavro** [MauricioRobayo/pascua#512]
I hope this message finds you well. I am a user of your  package, which I recently installed from the GitHub repository. First of all, I would like to thank you for your valuable contribution to the Node.js community with this excellent package.

I encountered a minor issue while trying to build the package using `npm run build`. The build process did not create the expected "dist" directory as anticipated.
<img width="1368" alt="Screenshot 2023-08-06 at 8 10 35 PM" src="https://github.com/MauricioRobayo/pascua/assets/4742672/8aa65110-2a5a-4f04-bd1a-09b636951e5e">

After investigating the root cause, I found that the problem lies in the "tsconfig.json" file.

The current "tsconfig.json" file has the following configuration:

```json
{
  "compilerOptions": {
    "target": "es5",
    // Other configuration options...
  }
}
```

To resolve the issue and generate the "dist" directory correctly, I made a small modification to the "tsconfig.json" file by changing the "target" option to:

```json
{
  "compilerOptions": {
    "target": "es2017",
    // Other configuration options...
  }
}
```

After applying this change, the "npm run build" command successfully generated the "dist" directory with the compiled output, and the package now works as expected.

I wanted to bring this to your attention, hoping that it might be helpful in addressing the issue and potentially making the necessary updates in the official package release very soon.

Thank you once again for your dedication to maintaining and improving [pascua](https://github.com/MauricioRobayo/pascua). If there is anything I can do to assist further or provide more information regarding this matter, please do not hesitate to reach out.

**Comment by MauricioRobayo** [comment]
The issue was related to a recent change I made in the github action to trigger an automated release, after generating the build and then downloading the artifact for the release the path was not set and the `dist` directory was not found.

Thanks for the PR as it is still an improvement, appreciate if you can validate that the latest version is working for you.

After merging your PR I had to trigger the release with another commit as the commit message did not satisfied the requirements, kept it as a minor release.
